version: '3.7'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/load_balance.conf:/etc/nginx/conf.d/default.conf:ro
      - /nginx/var/log/nginx/:/var/log/nginx/:rw
    restart: always
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginx

  apache_1:
    image: "httpd:bookworm"
    container_name: apache_1
    volumes:
      - ./apache/site1/:/usr/local/apache2/htdocs/
    restart: always
    networks:
      nginx:
        ipv4_address: 172.16.0.11

  apache_2:
    image: "httpd:bookworm"
    container_name: apache_2
    volumes:
      - ./apache/site2/:/usr/local/apache2/htdocs/
    restart: always
    networks:
      nginx:
        ipv4_address: 172.16.0.12

  apache_3:
    image: "httpd:bookworm"
    container_name: apache_3
    volumes:
      - ./apache/site3/:/usr/local/apache2/htdocs/
    restart: always
    networks:
      nginx:
        ipv4_address: 172.16.0.13

networks:
  nginx:
    driver: bridge
    ipam:
     config:
     - subnet: 172.16.0.0/24
       gateway: 172.16.0.1
