version: '3.7'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/load_balance.conf:/etc/nginx/conf.d/default.conf:ro
      - /nginx/var/log/nginx/:/var/log/nginx/:rw
    restart: always
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginx

  apache:
    image: "httpd:bookworm"
    container_name: apache
    volumes:
      - ./apache/sites/:/usr/local/apache2/htdocs/
      - ./apache/httpd.conf:/usr/local/apache2/httpd.conf:ro
    restart: always
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    networks:
      - nginx

networks:
  nginx:
    driver: bridge
    ipam:
     config:
     - subnet: 172.16.0.0/24
       gateway: 172.16.0.1
