version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/load_balance.conf:/etc/nginx/conf.d/default.conf:ro
      - /nginx/var/log/nginx/:/var/log/nginx/:rw
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  joomla_1:
    image: joomla:3.6.2-apache
    ports:
     - 80
    environment:
     - JOOMLA_DB_HOST=mysql_master:3306
     - JOOMLA_DB_USER=joomla
     - JOOMLA_DB_PASSWORD=joomla
     - JOOMLA_DB_NAME=joomla_db

  joomla_2:
    image: joomla:3.6.2-apache
    ports:
     - 80
    environment:
     - JOOMLA_DB_HOST=mysql_master:3306
     - JOOMLA_DB_USER=joomla
     - JOOMLA_DB_PASSWORD=joomla
     - JOOMLA_DB_NAME=joomla_db

  joomla_3:
    image: joomla:3.6.2-apache
    ports:
     - 80
    environment:
     - JOOMLA_DB_HOST=mysql_master:3306
     - JOOMLA_DB_USER=joomla
     - JOOMLA_DB_PASSWORD=joomla
     - JOOMLA_DB_NAME=joomla_db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - runner
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana:rw
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_INSTALL_PLUGINS=vonage-status-panel
    env_file:
      - ./grafana/config.monitoring