global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.
  external_labels:
      monitor: 'my-project'

rule_files:
  - 'alert.rules'
  - 'prometheus.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "10.110.16.22:9093"

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']